specVersion: 1.0.0
name: zenlink-exchange-subquery
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=1.2.1"
  query:
    name: "@subql/query"
    version: ">=1.1.1"
description: This project can be use as a starting point for moonriver network.
repository: https://github.com/zenlinkpro/zenlink-exchange-subquery
schema:
  file: ./schema.graphql
network:
  chainId: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  # dictionary: 'https://api.subquery.network/sq/subquery/moonbeam-dictionary'
  endpoint: wss://moonbeam.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 171252
    processor:
      file: './dist/moonbeamEvm.js'
      options:
        abi: Factory
        address: '0xF49255205Dfd7933c4D0f25A57D40B1511F92fEF'
    assets:
      Factory:
        file: ./src/abis/factory.json
      ERC20:
        file: ./src/abis/ERC20.json
      ERC20SymbolBytes:
        file: ./src/abis/ERC20SymbolBytes.json
      ERC20NameBytes:
        file: ./src/abis/ERC20NameBytes.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewPair
          kind: substrate/MoonbeamEvent
          filter:
            topics: 
              - PairCreated(address indexed token0,address indexed token1,address pair,uint256)
templates:
  - name: Pair
    kind: substrate/Moonbeam
    processor:
      file: './dist/moonbeamEvm.js'
      options:
        abi: Pair
    assets:
      Pair:
        file: ./src/abis/pair.json
      Factory:
        file: ./src/abis/factory.json
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleMint
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Mint(address indexed sender,uint256 amount0,uint256 amount1)
        - handler: handleBurn
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Burn(address indexed sender,uint256 amount0,uint256 amount1,address indexed to)
        - handler: handleSwap
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Swap(address indexed sender,uint256 amount0In,uint256 amount1In,uint256 amount0Out,uint256 amount1Out,address indexed to)
        - handler: handleTransfer
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
